### ISSUE TITLE
[plugins.json] Add cocoapods-dependency-graph

### ISSUE THREAD

**Issue by sueLan** [CocoaPods/cocoapods-plugins#116]
Please add the following entry to the `plugins.json` file:

```
{
  "gem": "cocoapods-dependency-graph",
  "name": "CocoaPods Dependency Graph",
  "author": "Rongyan Zheng",
  "url": "https://github.com/sueLan/cocoapods-dependency-graph",
  "description": "A Cocoapods plugin to create the dependency graph and help you manage dependencies in your project."
}
```

**Comment by igor-makarov** [comment]
Thanks for your contribution!  

Just a few notes before we can merge this:  
* The plugin doesn't appear to be on [RubyGems](https://rubygems.org). This would prevent most users from installing it. Please publish your gem to RubyGems.
* The Readme file lists that it has a dependency, `rgl`, but the `.gemspec` doesn't list this dependency. This means that, even if it was published, the dependency won't be installed with it and the plugin wouldn't work. Please add the dependency to the `.gemspec`.
* It appears that the plugin outputs its graph on every run of `pod install`. This would incur a performance hit during the course of regular development. My suggestion is moving the graph output to a subcommand (there already seems to be [a stub](https://github.com/sueLan/cocoapods-dependency-graph/blob/master/cocoapods-dependency-graph/lib/cocoapods-dependency-graph/command/graph.rb)).

**Comment by igor-makarov** [comment]
I also noticed that this isn't a PR but an Issue. Please [create a PR](https://github.com/CocoaPods/cocoapods-plugins/compare) to help us including your plugin.

**Comment by sueLan** [comment]
Hi, 
  sorry for the late reply. 

> The plugin doesn't appear to be on RubyGems. This would prevent most users from installing it. Please publish your gem to RubyGems.
[published it](https://rubygems.org/gems/cocoapods-dependency-graph)

> The Readme file lists that it has a dependency, `rgl`, but the .gemspec doesn't list this dependency. This means that, even if it was published, the dependency won't be installed with it and the plugin wouldn't work. Please add the dependency to the .gemspec.

[Added it](https://github.com/sueLan/cocoapods-dependency-graph/blob/e14363dc5aa1671374c1d2f6df6f79442d59dac1/cocoapods-dependency-graph/Gemfile#L8)

> It appears that the plugin outputs its graph on every run of pod install. This would incur a performance hit during the course of regular development. 

Yes. This plugin runs on every run of `pod install`.  I do it on purpose. 

- Usually, people run `pod install` for update the dependency pods. Using [post-install](https://github.com/sueLan/cocoapods-dependency-graph/blob/e14363dc5aa1671374c1d2f6df6f79442d59dac1/cocoapods-dependency-graph/lib/cocoapods_plugin.rb#L6) helps people update the dependency graph automatically. 
- Now, I use [dependency_output](https://github.com/sueLan/cocoapods-dependency-graph/blob/e14363dc5aa1671374c1d2f6df6f79442d59dac1/cocoapods-dependency-graph/lib/cocoapods_dependency_graph.rb#L22) to control the output format. Only one kind of output is generated. Beside, I use [install_context](https://github.com/sueLan/cocoapods-dependency-graph/blob/e14363dc5aa1671374c1d2f6df6f79442d59dac1/cocoapods-dependency-graph/lib/cocoapods_plugin.rb#L7) to construct the graph. The time cost is about O(nlogn). I think it is acceptable 

> My suggestion is moving the graph output to a subcommand (there already seems to be a stub).
Yes, It is a stub. I saw this plugin made a subcommand to generate the dependency graph. But in order to do so, it has to read the `Podspec` file and analyze it, [code](https://github.com/segiddins/cocoapods-dependencies/blob/a051265f46e23b00f315a436e148c483e2bb22ec/lib/pod/command/dependencies.rb#L50). It is more time-consuming from the users perspective.
