### ISSUE TITLE
Add cocoapods-links to plugins repo

### ISSUE THREAD

**Issue by mowens** [CocoaPods/cocoapods-plugins#42]
Details:

```
 {
   "gem":"cocoapods-links",
   "name":"Pod links",
   "author":"Mike Owens",
   "social_media_url":"https://twitter.com/mikejowens",
   "url":"https://github.com/mowens/cocoapods-links",
   "description":"A CocoaPods plugin to manage local development pods"
}
```

**Comment by segiddins** [comment]
@mowens could you please make a pull request doing this?

**Comment by segiddins** [comment]
Also, great job on the plugin! Could you shoot me an email/message me on twitter, I'd like to chat with you about it!

**Comment by mowens** [comment]
@segiddins Sorry about that. Here is the [PR](https://github.com/CocoaPods/cocoapods-plugins/pull/43).

I sent you an email so we can chat about the plugin.
