### ISSUE TITLE
[Idea] Annotate your Podfile

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoapods-plugins#50]
Similar to https://github.com/jgorset/label

**Comment by KrauseFx** [comment]
I like the idea :+1: 

Does this replace existing comments? Or what's your take on this?

**Comment by orta** [comment]
Probably looks for a `pod` reference, and sets the line above it to be a comment of the podspec.summary, easy to start with something simple

**Comment by neonichu** [comment]
@Karla-Isabel-Sandoval and @emkosz are doing this here: <https://github.com/Karla-Isabel-Sandoval/cocoapods-label>, so we can close the idea issue.
