### ISSUE TITLE
[Idea] Podfile.local

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoapods-plugins#53]
Take [this](https://github.com/artsy/eigen/blob/master/Podfile#L9-L11) pattern:

```
# Allows per-dev overrides
local_podfile = "Podfile.local"
eval(File.open(local_podfile).read) if File.exist? local_podfile
```

And make it systematic.

**Comment by neonichu** [comment]
that'll currently only work for the "main" target, I think, because multiple target blocks for the same target go :boom:

**Comment by orta** [comment]
legit, and that's a bad pattern IMO
