### ISSUE TITLE
[plugins.json] Add cocoapods-last_word

### ISSUE THREAD

**Issue by DmitryBespalov** [CocoaPods/cocoapods-plugins#57]
Please add the following entry to the `plugins.json` file:

```
{
  "gem": "cocoapods-last_word",
  "name": "CocoaPods Last_word",
  "author": "Dmitry Bespalov",
  "url": "https://github.com/zalando/cocoapods-last_word",
  "description": "Add real post-install hooks that execute after all cocoapods actions finish."
}
```

**Comment by segiddins** [comment]
Please make a pull request adding this :)

**Comment by diamondsky** [comment]
I have a question. I want to run plugin locally to test how it works. How do I do that?

**Comment by orta** [comment]
`gem install cocoapods-last_word` should get it in your global scope for `pod`. Otherwise you could use a Gemfile, and use `gem  "cocoapods-last_word"` and `cocoapods` in that and use `bundle exec pod install` to run it with it included.

**Comment by DmitryBespalov** [comment]
closing this issue because it is outdated
